from pydantic import BaseModel, Field
from typing import Dict, Optional, List

class DataBlueprint(BaseModel):
    """
    The Architectural Blueprint generated by the Scout Agent.
    The Builder Agent uses this to write the actual Python code.
    """
    source_name: str = Field(..., description="Unique name of the source (e.g. 'espn_nba')")
    base_url: str = Field(..., description="The target URL to fetch")
    
    # Strategy
    fetch_strategy: str = Field("http", description="Method to fetch: 'http' (generic), 'curl' (impersonate), or 'browser'")
    
    # Structure (The 'Where')
    root_selector: Optional[str] = Field(None, description="CSS selector for the main container (e.g. 'div.game')")
    
    # Fields (The 'What')
    # Mapping of logical_name -> selector_path
    # e.g. {"home_team": ".team.home .name", "score": ".score"}
    fields: Dict[str, str] = Field(default_factory=dict)
    
    # Context (The 'Why')
    domain_labels: Dict[str, str] = Field(default_factory=dict, description="Static labels to apply (e.g. {'sport': 'nba'})")
    
    description: str = Field("", description="Human readable notes about this source")
